services:
  - type: web
    name: ai-chat-server
    plan: free
    runtime: image
    image:
      url: ghcr.io/smashedr/ai-chat-server:latest
    dockerCommand: npm start
    #healthCheckPath: /app-health-check
    envVars:
      - key: MODEL
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_GENERATIVE_AI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
