name: "Deploy"

on:
  workflow_call:
    inputs: &inputs
      version:
        description: "Version Tag"
        required: false
        type: string
  workflow_dispatch:
    inputs: *inputs
  #workflow_run:
  #  workflows: ["Build"]
  #  types: [completed]

env:
  traefik-host: ai-chat.cssnr.com
  stack-file: docker-compose-swarm.yaml
  #stack-name: ${{ github.repository_owner }}-${{ github.event.repository.name }}
  stack-name: cssnr-${{ github.event.repository.name }}
  version: ${{ inputs.version || github.event.workflow_run.head_branch || github.ref_name }}

jobs:
  deploy:
    #if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    name: "Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    #environment:
    #  name: swarm
    #  url: https://ai-chat.cssnr.com/

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Debug event.json"
        if: ${{ !github.event.act }}
        continue-on-error: true
        run: cat "${GITHUB_EVENT_PATH}"
      - name: "Debug CTX github"
        if: ${{ !github.event.act }}
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"
      - name: "Debug Environment"
        if: ${{ !github.event.act }}
        continue-on-error: true
        run: env

      - name: "Debug 1"
        continue-on-error: true
        run: |
          echo "inputs.version: ${{ inputs.version }}"
          echo "github.event.workflow_run.head_branch: ${{ github.event.workflow_run.head_branch }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "env.version: ${{ env.version }}"

      - name: "Portainer Deploy"
        uses: cssnr/portainer-stack-deploy-action@v1
        env:
          version: ${{ env.version == 'master' && 'latest' || env.version }}
        with:
          url: ${{ secrets.PORTAINER_URL }}
          token: ${{ secrets.PORTAINER_TOKEN }}
          file: ${{ env.stack-file }}
          name: ${{ env.stack-name }}
          username: ${{ vars.GHCR_USER }}
          password: ${{ secrets.GHCR_PASS }}
          type: file
          env_data: |
            VERSION: "${{ env.version }}"
            STACK_NAME: "${{ env.stack-name }}"
            TRAEFIK_HOST: "${{ env.traefik-host }}"
            BASIC_AUTH: "${{ secrets.BASIC_AUTH }}"
            GOOGLE_GENERATIVE_AI_API_KEY: "${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}"
            OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
            MODEL: "gpt-5.4-nano"
            MAX_TOKENS: "1024"
            CORS_ORIGINS: |
              https://cssnr.github.io
              https://smashedr.github.io
              https://dev-static.cssnr.com
              https://django-files.github.io

      ## https://render.com/docs/deploy-hooks#deploying-from-an-image-registry
      #- name: "Deploy Image"
      #  uses: cssnr/web-request-action@v2
      #  continue-on-error: true
      #  env:
      #    version: ${{ env.version == 'master' && 'latest' || env.version }}
      #  with:
      #    url: ${{ secrets.RENDER_HOOK }}
      #    params: |
      #      imgURL: ghcr.io/${{ github.repository }}:${{ env.version }}
